name: courtbooking
services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: courtbooking-db
    environment:
      POSTGRES_DB: courtbooking
      POSTGRES_USER: courtbooking
      POSTGRES_PASSWORD: courtbooking
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
